### PR TITLE
Added file extension info overlay in list view

### PR DESCRIPTION
**Pull request by alexanghh**

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
This is causing a few issues:
image

**Comment by alexanghh** [comment]
Yes, noted that long extension may cover the filename hence the lower placement to minimize overlaps.

**Comment by mickael-kerjean** [comment]
If we publish something like this, I'll get an bug raised at some point. The reason why the file extension doesn't show up in list mode is I couldn't find a proper solution to work this out in the first place. There might be some option but we're not there yet.

**Comment by alexanghh** [comment]
An alternative would be to follow dropbox's method
- separate icon for known file types (doc, docx, pdf, mp3, etc)
- always show the file extension by hiding the middle portion of long filename "abc...xyz.pdf" and showing the full filename with mouseover dialog

**Comment by alexanghh** [comment]
Just wanted to note that I found a simpler solution which is to properly fix the ellipsis of filename to should file extension and size. However, there is still no way to display the full filename. 
I will do another pull request for this fix.

**Pull request closed without merging**
