### PR TITLE
Debian install

### PR DESCRIPTION
**Pull request by ymelois**
I have added the installation instructions for Filestash on Debian. It should be used for production.

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
I will be closing this as the related PR got [merged](https://github.com/mickael-kerjean/filestash-website/pull/33) (Thank you @sehnryr ). The reasoning of pushing that kind of script on the website and not in the repo is to facilitate the future maintenance of the project

**Comment by H4Z4RD-H42** [comment]
@sehnryr I followed the procedure, but it destroyed my server. I have a seedbox with Debian11 and I wanted to install Filestash without installing docker, I ran the commands as root and now it no longer works ruTorrent, Nextcloud and other programs are no longer reachable. What happened? How can I restore everything?

**Comment by ialexpw** [comment]
Agree with @H4Z4RD-H42 - I did a test with this script on a system and after installing cm-super, it attempts to wipe out _a lot_ of things as can be seen;

```
[1/1, ??:??/??:??] install: capt-of [2k]
running mktexlsr ...
done running mktexlsr.
tlmgr: package log updated: /usr/share/tinytex/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /usr/share/tinytex/texmf-var/web2c/tlmgr-commands.log
tlmgr: package repository http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: epstopdf-pkg
tlmgr: package repository http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: cm-super [63050k]
running mktexlsr ...
done running mktexlsr.
running updmap-sys ...
done running updmap-sys.
tlmgr: package log updated: /usr/share/tinytex/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /usr/share/tinytex/texmf-var/web2c/tlmgr-commands.log
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  galera-4* git* git-man* libaio1* libcgi-fast-perl* libcgi-pm-perl* libclone-perl* libconfig-inifiles-perl*
  libdbd-mariadb-perl* libdbi-perl* libencode-locale-perl* liberror-perl* libfcgi-bin* libfcgi-perl* libfcgi0ldbl*
  libgdbm-compat4* libhtml-parser-perl* libhtml-tagset-perl* libhtml-template-perl* libhttp-date-perl*
  libhttp-message-perl* libio-html-perl* liblwp-mediatypes-perl* libperl5.32* libterm-readkey-perl* libtimedate-perl*
  liburi-perl* mailcap* mariadb-client-10.5* mariadb-client-core-10.5* mariadb-server* mariadb-server-10.5*
  mariadb-server-core-10.5* mime-support* patch* perl* perl-modules-5.32* rsync* wget*
0 upgraded, 0 newly installed, 39 to remove and 0 not upgraded.
After this operation, 243 MB disk space will be freed.
(Reading database ... 51325 files and directories currently installed.)
Removing mariadb-server (1:10.5.19-0+deb11u2) ...
Removing mariadb-server-10.5 (1:10.5.19-0+deb11u2) ...
Removing galera-4 (26.4.11-0+deb11u1) ...
Removing git (1:2.30.2-1+deb11u2) ...
Removing git-man (1:2.30.2-1+deb11u2) ...
Removing mariadb-server-core-10.5 (1:10.5.19-0+deb11u2) ...
```

It's caused by

`apt-get purge -y --auto-remove perl wget`

Unsure why this is that necessary to have

**Comment by tmanok** [comment]
> EDIT: 1 day to re-install OS and everything else... I will stay far away from this tool, it destroyed my server.

No offence, but mate you really ought to have known that it was a foolish thing to do from the beginning. Basic common sense says:

1. Do not run random scripts off the internet as root... Ok, fine at least not without:
a) reviewing the code
b) understanding the code
c) verifying it wasn't written in the middle ages
2. Run it on a test system or on a fresh install only... Ideally, with restricted networking as a security measure.

...Does anyone know where to update the GPG key from? The filestash website is down for me right now and I'm preparing a Debian 12 installation. 

Cheers,


Tmanok

**Comment by mickael-kerjean** [comment]
> The filestash website is down for me right now and I'm preparing a Debian 12 installation.

There's issues with the vps provider at the moment, it's still working but only extremely slow. Also I will be migrating almost everything to a colo so as to get better performance with some hardware I control.

> ...Does anyone know where to update the GPG key from?

Seeing what other people are experiencing using the non standard install, I wouldn't advise anything else than the standard docker installation method that is documented and not use anything from the alternative installation method. Realistically maintaining install for every possible linux distribution from deb package, to rpm, to whatever flatpack or snap going through the AUR repository is way too much for myself to create and test when there's so much more to do to move the project forward. I guess, the path forward is either:

1. you're looking not to pay a cent => just use the plain docker image or create your own build

2. you really need something outside docker => I can get it to work through a support contract and we will spend time working out something that work for your exact needs.

**Pull request closed without merging**
