### PR TITLE
Extension of the image plugin with CGO build options for FreeBSD

### PR DESCRIPTION
**Pull request by MatthiasPetermann**
With the attached change, filestash can also be created on FreeBSD if the required static libraries are installed. I have successfully tested it on FreeBSD/amd64. To make it work, I had to duplicate the go files and create one variant for FreeBSD and one for Linux. I'm not sure if there is a more elegant way to do this, but if this is acceptable, it would be nice if you could accept this pull request.

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
That's very nice thank you. The plg_image_c is very bleeding edge and adding support for freebsd sounds very good although since your PR I've added support for gif thumbnail using libgif and that will probably cause some issues as well. Do you mind adding support for libgif with the new gif thumbnailer using the same approach you've done here? To my knowledge your PR is perfect, we're simply missing support for the gif thumbnailer 

In the same way as jpeg, heic, png and other raw format, it's based on another C program using libgif: https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_c/image_gif.c

If you have any question don't hesitate to reach out

**Comment by MatthiasPetermann** [comment]
Thanks for your response - seems I missed it in the first place. Sure, I will check out the latest revision and try to add libgif support as well. Kind regards, Matthias

**Comment by yonas** [comment]
@MatthiasPetermann Thanks for the PR.

@mickael-kerjean Are there any issues remaining to commit?

**Comment by yonas** [comment]
Rebased off latest HEAD: https://github.com/yonasBSD/filestash/commit/eac55772803d272b43becdeb4379c885a5f545d7

**Comment by mickael-kerjean** [comment]
there's conflicts that must be resolved

**Comment by yonas** [comment]
@mickael-kerjean Can you merge https://github.com/mickael-kerjean/filestash/pull/731 ?

**Comment by mickael-kerjean** [comment]
Done, thanks!

**Pull request closed without merging**
