### PR TITLE
Fix double encoding of file links

### PR DESCRIPTION
**Pull request by itsnotv**
Fix for #203

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
Hello and thank again for your help. 

To follow up, I haven't merged yet as there's quite some history with this part of the code:
1. [a first pull request](https://github.com/mickael-kerjean/filestash/pull/159) to fix some encoding issues from #157  
2. a few issues that seems to be linked #210 #203 #205 

As a consequence, before merging this I will need to write some tests to ensure this is all finally working. This will happen before 15th of November as I'm currently helping some of my family to get through some hard times.

**Comment by mickael-kerjean** [comment]
I made some tests and there's still some issues
screenshot_20191101_083821

**Comment by itsnotv** [comment]
I hope this if fixed soon. I love this app but I often run into issues opening files because of this bug.

**Comment by mickael-kerjean** [comment]
> I hope this is fixed soon

The pull request is a good beginning for a proper solution, I'm gonna start working on a solution that handle all the edge cases, it takes some time to get right, at this stage it should just be a few days away.

> Aren't the tests open source?

No, this is explained [here](https://github.com/mickael-kerjean/filestash/blob/master/CONTRIBUTING.md#tests) and from the [faq](https://www.filestash.app/docs/faq/#the-code-doesnt-have-tests--are-you-guys-cowboys)

**Pull request merged**
