### PR TITLE
feature (plg_backend_s3): add param for forcePathStyle

### PR DESCRIPTION
**Pull request by yanickxia**
Sorroy, i'm not good at webpage. i don't know how to add Placeholder for Select, today seems something ugly..
image

> Amazon S3 supports both virtual-hosted–style and path-style URL access in all AWS Regions.

close: #357

### CODE REVIEW

**Review by mickael-kerjean — APPROVED** [review]
LGTM

**Comment by mickael-kerjean** [comment]
I will have to revert this for now as it's breaking some e2e tests in weird ways, see https://github.com/mickael-kerjean/filestash/actions

**Comment by mickael-kerjean** [comment]
Can you make another PR? I didn't run the CI after you made the PR as I thought everything was good, my mistake

**Comment by yanickxia** [comment]
> Can you make another PR? I didn't run the CI after you made the PR as I thought everything was good, my mistake

OK, but i don't know how to fix  [test_e2e](https://github.com/mickael-kerjean/filestash/actions/runs/4648497030/jobs/8228347845)

**Comment by mickael-kerjean** [comment]
Yep, it's all my mistake, I should have tried to run the tests before merging but well ... We just migrate to github action a few weeks ago and I'm not super used to it yet.

If you can make another PR, there should be a way to run the tests from there

**Pull request merged**
