### PR TITLE
Fix s3 rename again

### PR DESCRIPTION
**Pull request by Bramas**
Commit 1f447dc7d0 fixed an error cause by a wrong url encoding of the space character but reintroduced the bug occurring with special characters (you can try to rename a file "testé.txt" to "test.txt" to see the error).

Now I understand why this occurred (it took me quiet some time!)

Due to special characters, we must url-encode names when moving files in S3, but, the standard QueryEscape from go encodes a space with a "+" character, which does not respect the RFC. The S3 api expects "%20"

There is no other standard function that behaves as expected as it is show in this snippet: https://go.dev/play/p/pOfrn-Wsq5

So the best way was to use QueryEscape  but replace "+" by "%20"

Now everything works!

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
The PR is causing issues with the space on rename. Example:
1. create a file named "testé.txt"
2. rename that file "te sté.txt"

**Comment by Bramas** [comment]
I just tried again with the official S3 api (I also tried with another S3 compatible storage).

Without my function urlEncodedPath: I get an error
With my function:: it works fine

I don't know where the difference with you comes from.

You can try my version using my fork https://github.com/bramas/filestash in the branch bramas-dev
which is build in the docker image bramas/filestash-dev

**Comment by Bramas** [comment]
Hi Mickael, were you able to reproduce the bug? or someone else? this is strange it happens to me while using the official docker image (I also tried with the last master branch).
Anyway, I can help if needed.

**Comment by mickael-kerjean** [comment]
I did try a few different s3 implementation to see if it doesn't introduce some other weird issues.
Ultimately, this is quite an awkward fix as this should be handled straight from the SDK or else what's the point of an SDK? This doesn't make much sense to me

**Comment by mickael-kerjean** [comment]
Also sorry for the delay in processing your PR, it was quite hectic in the last few months

**Comment by Bramas** [comment]
Yes it's weird that the sdk does not handle this, but this is what the doc is saying. Maybe it comes from the first implementation and now changing it would break things.
No problem, the delay is not an issue, I just send messages to offer my help if needed :)
Thanks for the work!

**Pull request merged**
