### PR TITLE
Implement thumbnailing for Gif, Webp, MP4, Webm

### PR DESCRIPTION
**Pull request by Happyrobot33**
Created a new plugin that allows for thumbnailing of videos. Added Gif and Webp support for the image thumbnailer. Fixed description on video transcoder toggle.

### CODE REVIEW

**Comment by Happyrobot33** [comment]
Im currently looking through the code to see if I can find where it returns the placeholder till the ProcessFileContentBeforeSend gets awnsered, so it can show the file type instead of the placeholder image till the thumbnail is generated, since it can take a while for FFMPEG to finish

**Comment by Happyrobot33** [comment]
if you get to this before I figure it out, basically what im thinking it should look like, is before the thumbnail is generated, it appears like a normal file does, but once the thumbnail has generated, it updates to the thumbnail instead

**Comment by Happyrobot33** [comment]
currently the server kind of gets hammered if there is alot of videos being requested, due to the time.Sleep implementation.
Even though there isnt more than CONCURRENT_TASKS instances of ffmpeg running, there will still be enough spinning processes as some point to cause an issue

```
  //check how many videos are currently being worked on, and if it is higher than the concurrent tasks, then wait
  for {
  files, err := os.ReadDir(filepath.Join(GetCurrentDir(), VideoCachePath))
  if err != nil {
	  Log.Error("[plugin video thumbnail] error reading video cache directory")
	  return reader, err, 0
  }
  count := 0
  for _, file := range files {
	  if strings.HasPrefix(file.Name(), "vid_") {
		  count++
	  }
  }
  if count < CONCURRENT_TASKS {
	  break
  }
  time.Sleep(20 * time.Second)
  }
```

**Comment by Happyrobot33** [comment]
all of these recent force pushes were in an attempt to lower the resolution, unfortunatly only powers of 2 look good and the next power of 2 likely wouldve been too small

**Comment by Happyrobot33** [comment]
Might need to implement some form of timeout on the requests, because if too many of them are sent from a browser at a time, the browsers connection to the server basically locks up due to the amount of pending requests

**Comment by Happyrobot33** [comment]
that.... took a while. I managed to fix the issue of the requests erroring though, so now thumbnail requests will actually update locally. it was all due to me writing more into the thumbnail buffer than just the thumbnail.

**Comment by Happyrobot33** [comment]
current issue: newly uploaded files dont get refreshed thumbnails

**Comment by Happyrobot33** [comment]
ok so I experimented, it is possible for FFmpeg to directly query a URL itself and be much faster, as it can ask for specific parts of the video it wants. my only issue is I am currently not able to get it to accept the current requests cookie, as it still returns a 401 authorization failure the relevant code I've been trying is this

```
	var fullURL string
	if req.TLS == nil {
		fullURL = "http://" + req.Host + req.URL.Path + "?" + req.URL.RawQuery
	} else {
		fullURL = "https://" + req.Host + req.URL.Path + "?" + req.URL.RawQuery
	}
	//remove the thumbnail parameter from the url
	fullURL = strings.ReplaceAll(fullURL, "&thumbnail=true", "")
	cmd := exec.Command("ffmpeg", "-i", fullURL, "-headers", "Cookie: " + cookie, "-vf", "thumbnail, scale=320:320: force_original_aspect_ratio=decrease", "-vframes", "1", "-c:v", "webp", "-f", "image2pipe", "pipe:1")

```
If you know to to get around the authorization failure let me know and ill implement it and test it @mickael-kerjean

**Comment by mickael-kerjean** [comment]
There's 2 very distinct things here:

# PART 1: IMAGE THUMBNAILING

You are reading everything in memory and transforming back onto a stream, not creating a thumbnail. The reason we're dynamically generating thumbnail is your browser can easily get to a stop if you try to browse a series of big images that hasn't been shrink down. Filestash is supposed to work with very large library without issues with minimal memory consumption which isn't the case here.

gif and webp are some extra image I'm planning to provide more support but we'd need to go do that part in plain C so as to make things more efficient. I did some benchmark with the go image processing, it is a few order of magnitude slower than plain C when it comes to work with images.

There's some existing image plugin which are doing thumnail as well and might work for your need if memory isn't a big concern: [plg_image_golang](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_golang/index.go), [plg_image_bimg](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_bimg) and what was the default until about a month ago [plg_image_light](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_light).

To give you an idea of the care that went onto the existing plugin, we've relied heavily on benchmark to shred any possible bit of performance you could get from the existing jpeg and png to the point where we've got a few order of magnitude faster than the typical imagemagick

# PART 2: VIDEO THUMBNAILING

The reason we haven't created such plugin yet is there's a lot of question that would need to be answer first. Things like:

1. How do you make it fast and light? ffmpeg can quickly be a pig that brings a raspberry pi to its knee under 5 seconds. How can we ensure things stays snappy on very low ressource platform?

2. How do you not break everything if a user is scrolling through a big list of videos? If you start to trigger many downloads in the same time, bandwidth usage might go to the roof, creating bottleneck and possibly high cost if you use something like S3 as a backend. Because we provide support for backend storage like S3 that charge for bandwidth, we're super careful about the default settings as we don't want to have someone to see their AWS bill go through the roof because creating some thumbnails meant downloading a crack ton of data. In fact I know of people who are in the media industry and store massive amount of media in there and I wouldn't want to cause them issues

4. How do you know the thumbnail that's about to be generated is not uggly? How do you pick which frame is ok to pick as a thumbnail? How much bandwidth do you need to use to generate a thumbnail?

It would be amazing to get an implementation that works well but there's a lot that would need to go onto there

**Comment by Happyrobot33** [comment]
>You are reading everything in memory and transforming back onto a stream, not creating a thumbnail. 

To this point, thats very fair, I just implemented them as they were something I thought were missing, but I also understand your point of it not being really well optimized to be considered ready for a main release.

>How do you make it fast and light? ffmpeg can quickly be a pig that brings a raspberry pi to its knee under 5 seconds. How can we ensure things stays snappy on very low ressource platform?

> How do you not break everything if a user is scrolling through a big list of videos? If you start to trigger many downloads in the same time, bandwidth usage might go to the roof, creating bottleneck and possibly high cost if you use something like S3 as a backend. Because we provide support for backend storage like S3 that charge for bandwidth, we're super careful about the default settings as we don't want to have someone to see their AWS bill go through the roof because creating some thumbnails meant downloading a crack ton of data. In fact I know of people who are in the media industry and store massive amount of media in there and I wouldn't want to cause them issues

FFMPEG actually supports direct links to a web input, allowing it to query only what it needs to generate the thumbnail. Plus, in my implementation, there is already UI toggles for it to be disabled, and it could come default disabled. I already have a disclaimer in there that it should only be used with a local backend, as its intensive. I also currently have implemented a system to only allow a certain number of videos at a time to be converted, however I want to rewrite this part as it uses a time.sleep for every single video, so if there is alot of waiting processes it quickly floods the CPU every X seconds

>How do you know the thumbnail that's about to be generated is not uggly? How do you pick which frame is ok to pick as a thumbnail? How much bandwidth do you need to use to generate a thumbnail?

This is done through the thumbnail filter in ffmpeg, which automatically trys to pick the best thumbnail frame it can find in the video. its not perfect, but does a pretty good job, but I dont think there is ever a "good" solution to this, as even youtube doesnt generate that good of default thumbnails for videos you upload. sidenote, I do want to add some kind of indicator to the generated video that indicates its a video instead of a image, but thats once the rest of the implementation is figured out.

A question I have as I want to further the performance of this but am not sure how to do what I need, is related to the last comment I put on here, about making my own request to the server with authorization, as then I can leverage FFMPEGs http input instead and make it so we dont have to download the entire video anymore, making it significantly faster. I already tried passing the request cookie to ffmpeg, bu it still returns 401. is there another way I could get this to work?

**Comment by Happyrobot33** [comment]
Well, I got the HTTP requesting working. I had the -headers parameter in the wrong place :(

**Comment by Happyrobot33** [comment]
now, with movies, it only takes a few seconds to finish the thumbnail now, instead of the minutes it took before due to having to download the whole thing

**Comment by Happyrobot33** [comment]
update, I have managed to make it blazingly fast now when it is used with a local network backend, sub 5 seconds for each thumbnail, most of the time 2 seconds per thumbnail on average, sometimes even quicker depending on the video. fully thumbnailed a folder of 144GB of video in about 5 minutes tops. Still need to check how much bandwidth is being used, but I dont think its much per video atleast

**Comment by Happyrobot33** [comment]
So, currently there has been a weird crash ive seen a few times with the current implementation, but cant reliably recreate it. it seems to be related to having too many http requests happening at the same time, but I cant really tell because I wasnt able to see the whole stack dump

**Comment by Happyrobot33** [comment]
@mickael-kerjean Here is a preview of it functioning on my own server

https://user-images.githubusercontent.com/32679887/197811869-e549afab-9c18-4e5c-8be3-bba19dca1e22.mp4

My server is setup with the file backend on the same local network, at 1gb/s speeds
this folder is loaded after a fresh restart of filestash, ensuring a cleared thumbnail cache
You can see I start with my browser cache disabled aswell
I am not on the local network that this server is running on, so I am not gaining anywhere near 1gb/s speeds to the browser

On the initial refresh, after listing all the files, you can watch as the plugin generates and sends the thumbnails for each of the videos (in this example 5 ffmpeg instances are allowed to convert at a time)
In this PR, the way the hover looks is added, but the width changes are not
The elephant video file is 1 hour long

The second refresh shows what a folder looks like once the filestash server has created cached thumbnails of all the videos, very fast

The third refresh is with the local browser cache on, showing that it is basically instant due to all of the images being loaded from the browser's cache instead

On a semi-unrelated note, I would like to propose possibly using the same implementation of the HTTP protocol in FFMPEG as I have for the video transcoding plugin, as it might lower the wait time required for the video to be downloaded to the server before playback significantly

**Comment by Happyrobot33** [comment]
@mickael-kerjean 

> Also I can't imagine how this could work with a setup with thousands of multiple hours long videos in weird format like avi, mov, flv

FFMPEG Automatically detects different formats, and i have tested it with quite a few formats already and it works just fine

> make sure bandwidth usage to generate the thumbnail doesn't go to the roof so as not to piss off people who use storage where you need to pay for bandwidth (like S3 and backblaze)

I already addressed this in the last comment I did, but this is already handled by the ffmpeg HTTP input. at most it only makes 3-4 requests, some for the file metadata, then the last request it does is for the actual frame. in theory this shouldnt be any heavier than the image thumbnailer.

> make sure the code behave well around the boundaries. I don't want someone to be able to bring my server down to a halt because his particular video is 3000h long or something weird like that.

You say this, yet the transcoder runs worse than this thumbnailer at requesting videos that size, and can take 30+ seconds to initialize a video. plus, the transcoder would likely do the same thing, because it is downloading the video to cache, this thumbnailer only makes the bare minimum requests needed

I added some profiling to the golang code and this is what it says
Clearly FFMPEG is taking up the 1 second return time, but I dont really think there is getting any much faster than that anyway, due to needing to still download the frame anyway
```
2022/10/27 15:00:32 SYST DEBUG [plugin video thumbnail] (Thumbnail Not Found Check Finished): 42.526µs
2022/10/27 15:00:32 SYST DEBUG [plugin video thumbnail] (FFMPEG Instance Check Finished): 5.099856ms
2022/10/27 15:00:33 HTTP 206 GET    2.2ms /api/files/cat?path=%2FArchive%2FOther%2F0001-1212.mp4
2022/10/27 15:00:33 HTTP 206 GET    4.7ms /api/files/cat?path=%2FArchive%2FOther%2F0001-1212.mp4
2022/10/27 15:00:34 HTTP 206 GET 1055.9ms /api/files/cat?path=%2FArchive%2FOther%2F0001-1212.mp4
2022/10/27 15:00:34 SYST DEBUG [plugin video thumbnail] (FFMPEG Finished): 1.137189135s
2022/10/27 15:00:34 SYST DEBUG [plugin video thumbnail] (Thumbnail Read Finished): 66.584µs
2022/10/27 15:00:34 SYST DEBUG [plugin video thumbnail] (Returned Thumbnail): 4.484µs
2022/10/27 15:00:34 HTTP 200 GET 1143.5ms /api/files/cat?path=%2FArchive%2FOther%2F0001-1212.mp4&thumbnail=true
```

> The other path outside ffmpeg which should be much faster is to extract the video metadata as it seems some video format like mp4 have some metadata which seem like they contains among other thigns a thumbnail:

This would work probably better being direct instead of through ffmpeg (from what I can tell ffmpeg actually uses this data if it exists) but the other problem with doing it directly is if that metadata does not exist. mp4 isnt required to have the cover metadata filled, and alot of the times it isnt

What I am proposing is that this be merged in default off, with warnings about data usage and possible slight slowdown on large folders of videos (even though I already account for that by only letting a certain number of ffmpeg instances run at a time) and allow the end user to decide if they want to take that downside

I also would love to have someone else test this on their own hardware and see what they get out of it, as the sample size of just my hardware isnt a good tell of its performance.

**Comment by mickael-kerjean** [comment]
There were a couple issue with this approach I wasn't happy about, then came the new PR #535. That got me thinking onto extending the plugin mechanism to provide a way to register a thumbnailer for a file type.

I've worked on this a couple days ago with a78e8176574472929dc253225c4c175515b1d9ea,  a simple example of such plugin can be found [here](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_golang/index.go). It looks like this:

``` golang
Hooks.Register.Thumbnailer("image/jpeg", thumbnailer{})  // <- register a thumbnailer for jpeg files

type thumbnailer struct{}

func (this thumbnailer) Generate(reader io.ReadCloser, ctx *App, res *http.ResponseWriter, req *http.Request) (io.ReadCloser, error) {
     // you have to return a thumbnailed version of reader 
}
```

I guess that's the only way we can be all happy as we can keep things that could potentially be in the hot path fast while enabling plugins to do more fancy things at the cost of resource usage. Hence if someone want to create a thumbnailer for pdf, excel, .... this is now all possible and those plugins aren't in core

If you think 1s is fine, I'll give you a hint of the craziness I've went for image thumbnailing. If you take jpeg, the thumbnailer runs some [C code I wrote](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_thumbnail/src/image_jpeg.c#L10-L100) leveraging tricks like DCT scaling for jpeg using plain old libjpeg, getting performance way above any other tool I've tried (and I've tried a lot of them). Basically the new thumbnailing plugin is a few order of magnitude faster than image magick at creating thumbnail and almost twice faster than [bimg](https://github.com/h2non/bimg) at this task even though it advertise itself as "fast high-level image processing" and "4x faster than using the quickest ImageMagick"

**Pull request closed without merging**
