### PR TITLE
Add an option to limit the number of simultaneous upload

### PR DESCRIPTION
**Pull request by Bramas**
It is currently set to 10. Now there is an option in the admin config page.

By setting it to 1 in my very small development server (0.5Go Ram and 1vCpu) I was able to still upload pretty big files.

I don't know if this is interesting in the main branch but it might interest someone, hence this PR.

(sorry VScode automatically applied some indentations and stuff like that in the middle of the file)

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
This is definitely interesting. Can you remove the automatic formatting from your commit so that it is self contained and doesn't overflow with everything else?

**Review by mickael-kerjean — CHANGES_REQUESTED** [review]
This is definitely interesting. Can you remove the automatic formatting from your commit so that it is self contained and doesn't overflow with everything else?

**Comment by Bramas** [comment]
sorry for the delay! 
I am not sure exactly how to edit the PR so I added a commit. I hope this is ok.

**Review by mickael-kerjean — APPROVED** [review]
LGTM

**Pull request merged**
