### PR TITLE
Resolve upload caching issue

### PR DESCRIPTION
**Pull request by robertDawson2**
This will clear the cache after file upload

### CODE REVIEW

**Comment by robertDawson2** [comment]
@mickael-kerjean this build is failing because of a gpg secret key issue, not the code itself:

`gpg: no default secret key: secret key not available`

Probably a similar issue with pull request https://github.com/mickael-kerjean/filestash/pull/381 as well

**Review by mickael-kerjean — CHANGES_REQUESTED** [review]
1. can you remove the comments?
2. to log the error: `Log.Error("couldn't remove multipartform data: %s", err.Error())`

**Comment by robertDawson2** [comment]
> 1. can you remove the comments?
> 2. to log the error: `Log.Error("couldn't remove multipartform data: %s", err.Error())`

Both changes added.

**Review by mickael-kerjean — APPROVED** [review]
LGTM

**Pull request merged**
