### PR TITLE
added ubuntu instructions + script

### PR DESCRIPTION
**Pull request by SRugina**
added instructions + sh script that does most things automatically for a user

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
Thank you for the contribution. The project documentation is located on [the website](https://www.filestash.app/docs/install-and-upgrade).
1. can you send a pull request there?
2. can you make the pull request as a link pointing either to: 
   1. another page you build within the documentation
   2. some external place: say medium or your personal website

**Comment by SRugina** [comment]
Sure, will do so when I find some time to write a medium article on it

**Comment by SRugina** [comment]
Just realised, my instructions are very impractical for development - only good for production as it uses the /tmp directory and is essentially a one-off script. I'd recommend anyone using it to take care when running the script. I'll be writing a medium article that details the ubuntu install process correctly (hopefully) very soon

**Comment by mckaygerhard** [comment]
@SRugina good point! filestash are a good gui to ftp! but that filestash is a shit on installation! docker are not good for multipurpose deploys at production!

**Comment by writingdeveloper** [comment]
@mckaygerhard @SRugina 

Is this method still works in 2021 right now?
I tried this method but it seems that there is no ./filestash directory.

**Comment by SRugina** [comment]
@writingdeveloper It has been a relatively long time since this PR was made, so I am not too surprised that it is out-of-date.

However, it looks like the [docker file](https://github.com/mickael-kerjean/filestash/blob/master/docker/Dockerfile) is now based on debian so you should be able to just use the commands within that on ubuntu (well, mostly).

@mickael-kerjean I'd suggest removing the link to this PR on [the website](https://www.filestash.app/docs/install-and-upgrade/#alternative-installation-methods) as this is out-of-date.

**Comment by phuongdzu** [comment]
Good product but cannot edit anything :(
I want to edit template in frontend but cannot. Anyone can customize? I hire to custom it

**Comment by mickael-kerjean** [comment]
Hey @phuongdzu I usually do some customisations for customers. Can you reach out to me at mickael@kerjean.me

**Comment by phuongdzu** [comment]
> 
> 
> Hey @phuongdzu I usually do some customisations for customers. Can you reach out to me at [mickael@kerjean.me](mailto:mickael@kerjean.me)
I sent Email but not any reply

**Comment by mickael-kerjean** [comment]
I didn't see any message from you. Can you fill this form: https://www.filestash.app/pricing/?modal=enterprise ?

**Comment by phuongdzu** [comment]
> 
> 
> I didn't see any message from you. Can you fill this form: https://www.filestash.app/pricing/?modal=enterprise ?

Yes, I send 3 times, both contact form and direct to your email
Do you have skype ot facebook?

**Comment by mickael-kerjean** [comment]
Do you confirm the email you filled the form ends with seekvn.com? I drop you a mail a few minutes ago

**Comment by phuongdzu** [comment]
> 
> 
> Do you confirm the email you filled the form ends with seekvn.com? I drop you a mail a few minutes ago

Yes sir, it's me

**Comment by phuongdzu** [comment]
Yes sir
    On Saturday, September 18, 2021, 01:55:40 PM GMT+7, Mickael ***@***.***> wrote:  
 
 


Do you confirm the email you filled the form ends with seekvn.com? I drop you a mail a few minutes ago

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mckaygerhard** [comment]
@writingdeveloper 
> I tried this method but it seems that there is no ./filestash directory.

please! is the filestat exec .. piff.. 

this method still works and  @SRugina  has right you can use also the docker inside commands..

**Pull request closed without merging**
