### PR TITLE
use fastzip replace the zip

### PR DESCRIPTION
**Pull request by zhucan**
original zip:
AhHrFwFF8e

fast zip:
hBQxXUidlv

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
It looks cool and the screenshot looks very appealing but if this implementation is plain better and faster with no drawbacks, it makes me wonder why this isn't in the standard library instead?

**Comment by microyahoo** [comment]
Hi, @mickael-kerjean, There are many good libraries that can provide better performance than the standard library, such as [jsoniter](https://github.com/json-iterator/go), [protobuf](https://github.com/protocolbuffers/protobuf), etc.

**Comment by mickael-kerjean** [comment]
If we take the infamous gin example, it's faster because it's not compliant with the HTTP specs. Whenever I see a dropin replacement I always wonder what is the cons of that implementation compared to the standard library. I might be wrong but if another implementation is plain better I would assume the golang maintainer are happy to merge it in the standard library or at least that was my experience fixing an issue in a package from the standard library a couple years ago.

**Comment by mickael-kerjean** [comment]
I'm closing this with the hope that whatever improvement coming from that library will eventually be making its way onto the standard library as this should be the right place to make a PR for

**Pull request closed without merging**
